services:
  - type: web
    name: slack-reaction-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: MESSAGE_TS
        sync: false

